apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  PORT: "5050"
  RABBIT_SERVICE: "rabbitmq"
  MONGO_URI: "mongodb://host.minikube.internal:27017/videosDB"
  MP3_MONGO_URI: "mongodb://host.minikube.internal:27017/mp3DB"
  AUTH_BASE_URL: "http://auth:5051/api/auth"
  # AMQP_URL: "amqp://localhost:5672"
  VIDEO_QUEUE: "videoQueue"
  MP3_QUEUE: "mp3Queue"
